name: linktest

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Node ${{ matrix.node }} / ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14.x]
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: linkcheck
        run: |
          npm install
          mkdir ./out
          npm run linkcheck | grep BROKEN > ./out/link_check_result.txt
        continue-on-error: true
      - name: grep-result
        id: result
        run: |
          BROKEN_RESULT="$(cat ./out/link_check_result.txt | grep BROKEN)"
          BROKEN_RESULT="${BROKEN_RESULT//$'\n'/\\n}"
          echo "::set-output name=BROKEN_RESULT::$BROKEN_RESULT"
      - name: issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RESULT: ${ cat ./out/link_check_result.txt }
        with:
          filename: .github/issue-linkcheck.md
