name: Issue Broken Link

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: link check
        run: |
          npm install broken-link-checker
          npx broken-link-checker https://akashic-games.github.io/ -o --requests 1 | grep BROKEN > ./link_check_result.txt
        continue-on-error: true
      - name: save result
        id: result
        run: |
          BROKEN_RESULT="$(cat ./link_check_result.txt)"
          BROKEN_RESULT="${BROKEN_RESULT//$'\n'/'%0A'}"
          echo "::set-output name=BROKEN_RESULT::$BROKEN_RESULT"
      - name: count result
        id: count
        run: |
          echo "::set-output name=count::$(cat ./link_check_result.txt | wc -l)"
      - name: create issue
        if: steps.count.outputs.count > 0
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RESULT: ${{ steps.result.outputs.BROKEN_RESULT }}
        with:
          filename: .github/issue-linkcheck.md
          update_existing: true

