name: linktest

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Node ${{ matrix.node }} / ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14.x]
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: linkcheck
        id: linkcheck
        run: |
          npm install
          RESULT = `npm run linkcheck | grep BROKEN`
          echo "::set-output name=RESULT::$RESULT"
        continue-on-error: true
      - name: issue
        uses: JasonEtco/create-an-issue@v2
        if: steps.linkcheck.outcome == 'failure'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RESULT: ${{ env.RESULT }} # テンプレート内で {{ env.XXX }} の形式で値を参照
        with:
          filename: .github/linkcheck.md    
